name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
  RUSTDOCFLAGS: "-Cpanic=abort"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cockroach:
        image: timveil/cockroachdb-single-node:latest
        env:
          DATABASE_NAME: test
        ports:
          - 26257:26257

    steps:
      - name: Checkout repo.
        uses: actions/checkout@v3
      - name: Install Rust toolchain.
        uses: dtolnay/rust-toolchain@stable
      - name: set environment variables
        run: echo "DATABASE_URL=${{ secrets.DB }}" > .env.test
      - name: Install diesel_cli.
        run: cargo install diesel_cli --no-default-features --features postgres
      - name: Run build
        run: cargo build
      - name: Run tests.
        run: bash test.sh
      - name: Run tests again (also test migration revert).
        run: bash test.sh